# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant::Config.run do |config|
  config.vm.box = "lucid64"
  config.vm.box_url = "http://files.vagrantup.com/lucid64.box"
  config.vm.host_name = "sshnode"
  config.vm.network :hostonly, "10.0.0.50"
  ## config.vm.forward_port 80, 8080
  config.vm.share_folder "shared", "/shared", "../shared"
  config.vm.provision :chef_solo do |chef|
    chef.cookbooks_path = "../chef/cookbooks"
    chef.roles_path = "../chef/roles"
    chef.add_recipe "apt"
    chef.add_recipe "python"
    chef.add_recipe "jip-users"
  end
end
