# -*- mode: ruby -*-
# vi: set ft=ruby :


slurm_cfg = {
    :slurm => {
        :master_addr =>"10.0.0.20",
        :computes => ["slmaster"],
        :compute_addrs => ["10.0.0.20"]
    },
    :nfs => {
        :headnode_addr => "10.0.0.20",
        :clients => ["10.0.0.20"]
    }
}
Vagrant::Config.run do |config|
    config.vm.box = "lucid64"
    config.vm.box_url = "http://files.vagrantup.com/lucid64.box"
    config.vm.host_name = "slmaster"
    config.vm.network :hostonly, "10.0.0.20"
    # config.vm.forward_port 80, 8080
    config.vm.share_folder "shared", "/shared", "../shared"
    config.vm.share_folder "code", "/code", "../../jip-server"
    config.vm.provision :chef_solo do |chef|
        chef.cookbooks_path = "../chef/cookbooks"
        chef.roles_path = "../chef/roles"
        chef.add_recipe "apt"
        chef.add_recipe "python"
        chef.add_recipe "jip-users"
        chef.add_recipe "slurm-mpi-cluster"
        chef.add_role "slurm-headnode"
        chef.add_role "slurm-computenode"
        chef.json = slurm_cfg
    end
end
